project: MIST
seed: 17

dataset:
  fp_names: ["morgan4096"]
  data_folder: "/path/to/MS_processing/data_BM/mist/"
  dataset: "massspecgym"
  cache_featurizers: True
  spec_features: "peakformula"
  mol_features: "fingerprint"
  dataset_type: "default"
  cls_type: "ms1"
  magma_aux_loss: True
  magma_modulo: 512

model:
  name: "mist"
  results_dir: "/path/to/ML_MS_analysis/FP_prediction/mist/best_models"

train_params:
  learning_rate: 0.00077
  lr_decay_frac: 0.9
  weight_decay: 1e-7
  scheduler: False
  
train_settings: 
  batch_size: 512
  num_workers: 4
  augment_data: False  

trainer:
  max_epochs: 200
  devices: 2
  log_every_n_steps: 5
  accelerator: "gpu"
  gradient_clip_val: 5 

callbacks: 
  patience: 20 
  val_monitor: "val_bce_loss"
